language: minimal
if: branch = master

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm version

script:
  - mkdir releases
  # TODO: Package only the modified charts
  - for i in $(find charts -maxdepth 1 -type d) ; do helm lint $i && helm package $i -d releases ; done
  - cd releases
  - helm repo index .

deploy:
  provider: pages
  local_dir: releases
  verbose: true
  keep_history: true
  on:
    branch: master

