apiVersion: v2
name: refractr
description: A Helm chart for the refractr redirect application
type: application
# Chart version, bump for any changes
version: 0.2.9
# appVersion specifies the docker image to pull
appVersion: dev-1.2.3
