apiVersion: v1
kind: Service
metadata:
  name: {{ include "refractr.fullname" . }}
  labels:
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  selector:
    {{- if .Values.service.selectorLabels }}
    {{ toYaml .Values.service.selectorLabels }}
    {{- end }}
