{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $release_name }}-{{ .Values.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $release_name }}
            cron: {{ .Values.name }}
        spec:
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            name: {{ .Values.name }}
            {{- with .Values.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- if .Values.command }}
            command: {{ .Values.command }}
            {{- end }}
            {{- with .Values.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with .Values.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
